# Dependabot configuration for Wealth Manager
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 10
    reviewers:
      - "kuoyaoming"
    assignees:
      - "kuoyaoming"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.google.dagger:hilt-android"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
    reviewers:
      - "kuoyaoming"
    assignees:
      - "kuoyaoming"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # Android Gradle Plugin
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
    reviewers:
      - "kuoyaoming"
    assignees:
      - "kuoyaoming"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "android"
      - "gradle"
    # Focus on Android-specific dependencies
    target-branch: "main"
    groups:
      android-dependencies:
        patterns:
          - "com.android.*"
          - "androidx.*"
          - "com.google.android.*"
