blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/kuoyaoming/Wealth-Manager/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/kuoyaoming/Wealth-Manager/tree/main/docs
    about: Check our documentation for setup and usage guides
  - name: 🔒 Security Issues
    url: mailto:security@wealthmanager.app
    about: Report security vulnerabilities privately
