name: Android CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '**'
  pull_request:

permissions:
  contents: write

jobs:
  debug:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;36.1.0" || sdkmanager --install "build-tools;35.0.0"

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Compute version (beta)
        shell: bash
        run: |
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)"
          BASE_NAME="${TAG#v}"
          SHORT_SHA="$(git rev-parse --short HEAD)"
          VERSION_NAME="${BASE_NAME}-beta.${GITHUB_RUN_NUMBER}+${SHORT_SHA}"
          echo "WM_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "WM_VERSION_CODE=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Run code quality checks
        run: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:codeQualityCheck --no-daemon --stacktrace

      - name: Build app and wear (Debug)
        run: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:assembleDebug :wear:assembleDebug --no-daemon --stacktrace

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload wear artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wear-debug-apk
          path: wear/build/outputs/apk/debug/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;36.1.0" || sdkmanager --install "build-tools;35.0.0"

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Decode Android keystore
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > keystore.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Compute version (release)
        shell: bash
        run: |
          TAG="$(git describe --tags --abbrev=0)"
          VERSION_NAME="${TAG#v}"
          echo "WM_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "WM_VERSION_CODE=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Run code quality checks (Release)
        run: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:codeQualityCheck --no-daemon --stacktrace

      - name: Build release bundles and APK
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:bundleRelease :app:assembleRelease --no-daemon --stacktrace

      - name: Upload release bundles
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/mapping/release/mapping.txt

      - name: Compute checksums
        run: |
          set -e
          cd app
          echo "Generating SHA256 checksums..."
          sha256sum build/outputs/bundle/release/*.aab > SHA256SUMS.txt
          sha256sum build/outputs/apk/release/*.apk >> SHA256SUMS.txt
          if [ -f build/outputs/mapping/release/mapping.txt ]; then
            sha256sum build/outputs/mapping/release/mapping.txt >> SHA256SUMS.txt
          fi
          cat SHA256SUMS.txt

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ env.WM_VERSION_NAME }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
            app/build/outputs/mapping/release/mapping.txt
            app/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
