name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          set -euo pipefail
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip
          rm -f cmdtools.zip
          mv cmdline-tools latest
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"
          yes | sdkmanager --licenses
          yes | sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;36.1.0" \
            "build-tools;34.0.0"

      - name: Prepare local.properties
        run: |
          echo "FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" > local.properties
          echo "EXCHANGE_RATE_API_KEY=${{ secrets.EXCHANGE_RATE_API_KEY }}" >> local.properties

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Release APKs
        run: |
          ./gradlew --version
          ./gradlew :app:assembleRelease :wear:assembleRelease --stacktrace --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            app/build/outputs/apk/release/*.apk
            wear/build/outputs/apk/release/*.apk
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Proguard mapping (app)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-proguard-mapping
          path: app/build/outputs/mapping/release/mapping.txt
          if-no-files-found: warn
          retention-days: 7
