name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;36.1.0" || sdkmanager --install "build-tools;35.0.0"

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Build app and wear (Debug)
        run: ./gradlew :app:assembleDebug :wear:assembleDebug --no-daemon --stacktrace

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload wear artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wear-debug-apk
          path: wear/build/outputs/apk/debug/*.apk
