name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        api-level: [34, 35]
        target: [google_apis, google_apis_playstore]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-${{ matrix.api-level }}" "build-tools;35.0.0"

      - name: Grant Gradle permissions
        run: chmod +x gradlew

      - name: Compute version
        shell: bash
        run: |
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)"
          BASE_NAME="${TAG#v}"
          SHORT_SHA="$(git rev-parse --short HEAD)"
          VERSION_NAME="${BASE_NAME}-test.${GITHUB_RUN_NUMBER}+${SHORT_SHA}"
          echo "WM_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "WM_VERSION_CODE=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Run unit tests
        run: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:testDebugUnitTest --no-daemon --stacktrace

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew -PwmVersionName=${{ env.WM_VERSION_NAME }} -PwmVersionCode=${{ env.WM_VERSION_CODE }} :app:connectedDebugAndroidTest --no-daemon --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-api-${{ matrix.api-level }}-${{ matrix.target }}
          path: |
            app/build/reports/tests/
            app/build/outputs/androidTest-results/
